class LoginFormKey:
    EMPLOYEE_NAME = "EmployeeName"
    EMPLOYEE_PASSWORD = "EmployeePassword"
    E_MAIL = "Email"
    OCCUPATION = "Occupation"
    ENTRUST_CUSTOMER = "EntrustCustomer"
    RECEIVE_CUSTOMER = "ReceiveCustomer"
    VOYAGE = "Voyage"
    ENTRUST_CUSTOMER_NAME = "EntrustCustomerName"
    RECEIVE_CUSTOMER_NAME = "ReceiveCustomerName"
    VOYAGE_NAME = "VoyageName"
    TRAILER_GROUP = "TrailerGroup"
    BAOGUAN_HANG = "BaoGuanHang"
    REGISTER = "Register"
    CONTAINER_TYPE = "ContainerSize"
    CONTAINER_COUNT = "ContainerCount"
    WEIGHT = "Weight"
